version: '3.8'

services:
  postgres:
    container_name: postgres-sql
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: parolation
      POSTGRES_DB: notification_management
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  app:
    container_name: notifications
    image: whitewiz/notifications:test
    environment:
      DATABASE_NAME: notification_management
      USERNAME: postgres
      POSTGRES_PASSWORD: parolation
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: