spring:
  application:
    name: notifications

  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    username: ${USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---

server:
  tomcat:
    threads:
      max: 100
      min-spare: 10

springdoc:
  api-docs:
    enabled: true
    path: /swagger/docs
  swagger-ui:
    path: /swagger/ui.html
---

logging:
  level:
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari.HikariDataSource: DEBUG